### ISSUE TITLE
Issue with CLI executing with gpt-4-turbo-v

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#364]
I can run the script in samples/src/vision/describe-image.genai.js in VSCode and it correctly executes, but when I try to run it from the CLI in bash in a codespace, I get this error.  Note that I first cd into src/vision and then run the CLI command:

@bzorn ➜ .../packages/sample/src/vision (main) $ npx --yes genaiscript run describe-image "src/vision/image001.png"
prompting model gpt-4-turbo-v
Model 'gpt-4-turbo-v' does not support chat.
name: Error
stack: >-
  Error: Model 'gpt-4-turbo-v' does not support chat.
      at _GptEncoding.encodeChatGenerator (/workspaces/genaiscript/packages/cli/built/genaiscript.cjs:97622:13)
      at encodeChatGenerator.next (<anonymous>)
      at _GptEncoding.encodeChat (/workspaces/genaiscript/packages/cli/built/genaiscript.cjs:97658:21)
      at estimateChatTokens (/workspaces/genaiscript/packages/cli/built/genaiscript.cjs:97738:24)
      at runTemplate (/workspaces/genaiscript/packages/cli/built/genaiscript.cjs:112273:22)
      at async _Command.runScript (/workspaces/genaiscript/packages/cli/built/genaiscript.cjs:123292:11)

- A receipt from Redmond Petco
- A white wall- A receipt from Redmond Petco
- A white wall
genaiscript generated 13 tokens
@bzorn ➜ .../packages/sample/src/vision (main) $

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/genaiscript/commit/25e3d4a9bb973147ae2e6a904a83dccacd62a131
